#!/bin/sh

set -e

echo "Removing old files..."
rm -f dosbox-staging*
rm -Rf fsbuild/_build

echo "Downloading dosbox-staging-0.78.1.tar.gz..."
URL=https://github.com/dosbox-staging/dosbox-staging/archive/refs/tags/v0.78.1.tar.gz
SHA256=dcd93ce27f5f3f31e7022288f7cbbc1f1f6eb7cc7150c2c085eeff8ba76c3690
python3 fsbuild/download.py "$URL" sha256:$SHA256

echo "Extracting dosbox-staging-0.78.1.tar.gz..."
mkdir -p fsbuild/_build
cd fsbuild/_build
rm -Rf dosbox-staging-0.78.1 dosbox-staging-src
tar xf ../_sources/v0.78.1.tar.gz
mv dosbox-staging-0.78.1 dosbox-staging-src

echo "Bootstrap done"
